apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  ports:
    - port: 80
  selector:
    app: mediawiki
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      containers:
      - image: mediawiki:1.34
        name: mediawiki
        env:
        - name: MEDIAWIKI_DB_HOST
          value: mediawiki-mysql
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: mediawiki
        volumeMounts:
        - name: mediawiki-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: mediawiki-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
